### ISSUE TITLE
Regression with SE2 type as Float64

### ISSUE THREAD

**Issue by Affie** [dehann/TransformUtils.jl#35]
@dehann, what is the reason for changing this back to hardcoded Float64, its the cause of https://github.com/JuliaRobotics/IncrementalInference.jl/issues/467#issuecomment-764807956

from this commit https://github.com/dehann/TransformUtils.jl/commit/31b95af951bdf470bd09e53beee9b9698bffbb02

https://github.com/dehann/TransformUtils.jl/blob/d84c5b5618e1289b53814962fad44a8dda5fcf85/src/TransformUtils.jl#L842

**Comment by dehann** [comment]
I cannot remember why I had to force it back, i do recall making the commit with comment "force Float64".  I think type inference was not able to pin down a type which resulted in some problem.  Think we can try "P <: Real" again and see if the problem comes up again.  Agree the force should not be necessary, apologies for not putting in a better comment

**Comment by dehann** [comment]
we should just test properly through all repo's and make sure there are no name conflicts because SE2 could be anywhere

**Comment by Affie** [comment]
Ok, I pinned my local TU @ v0.2.5 for parametric to work again. 

I'll see where it is used

**Comment by Affie** [comment]
Perhaps something like this was the reason 
```julia
julia> SE2([ 0, 0, 0])
3×3 Matrix{Int64}:
 1  0  0
 0  1  0
 0  0  1
```

**Comment by dehann** [comment]
ah don't recall unfortunately.  Sure we will find it again.  want to avoid the refactor of TU onto CT until after RoME 244 if possible, but maybe if everything in TU was against Real it'll be okay.
